[package]
name = "vergen"
version = "0.1.1-pre.0"
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "Generate version related functions"
documentation = "http://rustyhorde.github.io/vergen/vergen/vergen/index.html"
homepage = "http://rustyhorde.github.io/vergen"
repository = "https://github.com/rustyhorde/vergen"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["rust","rustyhorde","vergen"]

[dependencies]
blastfig = "~0.3.3"
clippy = { version = "~0.0.30", optional = true }
time = "~0.1.34"
