[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "Generate version related functions"
documentation = "http://docs.rs/vergen"
homepage = "http://github.com/rustyhorde/vergen"
keywords = ["version", "generation"]
license = "MIT/Apache-2.0"
name = "vergen"
readme = "README.md"
repository = "https://github.com/rustyhorde/vergen"
version = "0.1.2-pre.0"

[dependencies]
bitflags = "0"
chrono = "0"
error-chain = "0"
